# This file is automatically generated by pyo3_stub_gen
# ruff: noqa: E501, F401

import typing

class ModelInputProviderABC:
    def __new__(cls,): ...
    def get_joint_angles(self, _joint_names:typing.Sequence[str]) -> typing.Any:
        ...

    def get_joint_angular_velocities(self, _joint_names:typing.Sequence[str]) -> typing.Any:
        ...

    def get_projected_gravity(self) -> typing.Any:
        ...

    def get_accelerometer(self) -> typing.Any:
        ...

    def get_gyroscope(self) -> typing.Any:
        ...


class PyModelInputProvider:
    def __new__(cls,obj:typing.Any): ...
    ...

def get_version() -> str:
    ...

