# This file is automatically generated by pyo3_stub_gen
# ruff: noqa: E501, F401

import numpy
import numpy.typing
import typing

class ModelProviderABC:
    def __new__(cls,): ...
    def get_joint_angles(self, joint_names:typing.Sequence[str]) -> numpy.typing.NDArray[numpy.float32]:
        ...

    def get_joint_angular_velocities(self, joint_names:typing.Sequence[str]) -> numpy.typing.NDArray[numpy.float32]:
        ...

    def get_projected_gravity(self) -> numpy.typing.NDArray[numpy.float32]:
        ...

    def get_accelerometer(self) -> numpy.typing.NDArray[numpy.float32]:
        ...

    def get_gyroscope(self) -> numpy.typing.NDArray[numpy.float32]:
        ...

    def take_action(self, action:numpy.typing.NDArray[numpy.float32]) -> None:
        ...


class PyModelProvider:
    ...

class PyModelRunner:
    def __new__(cls,model_path:str, provider:ModelProviderABC): ...
    def init(self) -> numpy.typing.NDArray[numpy.float32]:
        ...

    def step(self, carry:numpy.typing.NDArray[numpy.float32]) -> tuple[numpy.typing.NDArray[numpy.float32], numpy.typing.NDArray[numpy.float32]]:
        ...


def get_version() -> str:
    ...

