"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
"""

import builtins
import collections.abc
import google.protobuf.descriptor
import google.protobuf.internal.containers
import google.protobuf.internal.enum_type_wrapper
import google.protobuf.message
import sys
import typing

if sys.version_info >= (3, 10):
    import typing as typing_extensions
else:
    import typing_extensions

DESCRIPTOR: google.protobuf.descriptor.FileDescriptor

class _JointPositionUnit:
    ValueType = typing.NewType("ValueType", builtins.int)
    V: typing_extensions.TypeAlias = ValueType

class _JointPositionUnitEnumTypeWrapper(google.protobuf.internal.enum_type_wrapper._EnumTypeWrapper[_JointPositionUnit.ValueType], builtins.type):
    DESCRIPTOR: google.protobuf.descriptor.EnumDescriptor
    DEGREES: _JointPositionUnit.ValueType  # 0
    RADIANS: _JointPositionUnit.ValueType  # 1

class JointPositionUnit(_JointPositionUnit, metaclass=_JointPositionUnitEnumTypeWrapper):
    """--------------- *
    Joint Positions *
    ---------------
    """

DEGREES: JointPositionUnit.ValueType  # 0
RADIANS: JointPositionUnit.ValueType  # 1
global___JointPositionUnit = JointPositionUnit

class _JointVelocityUnit:
    ValueType = typing.NewType("ValueType", builtins.int)
    V: typing_extensions.TypeAlias = ValueType

class _JointVelocityUnitEnumTypeWrapper(google.protobuf.internal.enum_type_wrapper._EnumTypeWrapper[_JointVelocityUnit.ValueType], builtins.type):
    DESCRIPTOR: google.protobuf.descriptor.EnumDescriptor
    DEGREES_PER_SECOND: _JointVelocityUnit.ValueType  # 0
    RADIANS_PER_SECOND: _JointVelocityUnit.ValueType  # 1

class JointVelocityUnit(_JointVelocityUnit, metaclass=_JointVelocityUnitEnumTypeWrapper):
    """---------------- *
    Joint Velocities *
    ----------------
    """

DEGREES_PER_SECOND: JointVelocityUnit.ValueType  # 0
RADIANS_PER_SECOND: JointVelocityUnit.ValueType  # 1
global___JointVelocityUnit = JointVelocityUnit

class _JointTorqueUnit:
    ValueType = typing.NewType("ValueType", builtins.int)
    V: typing_extensions.TypeAlias = ValueType

class _JointTorqueUnitEnumTypeWrapper(google.protobuf.internal.enum_type_wrapper._EnumTypeWrapper[_JointTorqueUnit.ValueType], builtins.type):
    DESCRIPTOR: google.protobuf.descriptor.EnumDescriptor
    NEWTON_METERS: _JointTorqueUnit.ValueType  # 0

class JointTorqueUnit(_JointTorqueUnit, metaclass=_JointTorqueUnitEnumTypeWrapper):
    """-------------- *
    Joint Torques *
    --------------
    """

NEWTON_METERS: JointTorqueUnit.ValueType  # 0
global___JointTorqueUnit = JointTorqueUnit

class _IMUValueType:
    ValueType = typing.NewType("ValueType", builtins.int)
    V: typing_extensions.TypeAlias = ValueType

class _IMUValueTypeEnumTypeWrapper(google.protobuf.internal.enum_type_wrapper._EnumTypeWrapper[_IMUValueType.ValueType], builtins.type):
    DESCRIPTOR: google.protobuf.descriptor.EnumDescriptor
    QUATERNION: _IMUValueType.ValueType  # 0
    EULER_ANGLES: _IMUValueType.ValueType  # 1

class IMUValueType(_IMUValueType, metaclass=_IMUValueTypeEnumTypeWrapper):
    """--- *
    IMU *
    ---
    """

QUATERNION: IMUValueType.ValueType  # 0
EULER_ANGLES: IMUValueType.ValueType  # 1
global___IMUValueType = IMUValueType

@typing.final
class TensorSchema(google.protobuf.message.Message):
    """------ *
    Tensor *
    ------
    """

    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    SHAPE_FIELD_NUMBER: builtins.int
    @property
    def shape(self) -> google.protobuf.internal.containers.RepeatedScalarFieldContainer[builtins.int]: ...
    def __init__(
        self,
        *,
        shape: collections.abc.Iterable[builtins.int] | None = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["shape", b"shape"]) -> None: ...

global___TensorSchema = TensorSchema

@typing.final
class TensorValue(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    DATA_FIELD_NUMBER: builtins.int
    @property
    def data(self) -> google.protobuf.internal.containers.RepeatedScalarFieldContainer[builtins.float]: ...
    def __init__(
        self,
        *,
        data: collections.abc.Iterable[builtins.float] | None = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["data", b"data"]) -> None: ...

global___TensorValue = TensorValue

@typing.final
class JointPositionValue(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    NAME_FIELD_NUMBER: builtins.int
    VALUE_FIELD_NUMBER: builtins.int
    UNIT_FIELD_NUMBER: builtins.int
    name: builtins.str
    value: builtins.float
    unit: global___JointPositionUnit.ValueType
    def __init__(
        self,
        *,
        name: builtins.str = ...,
        value: builtins.float = ...,
        unit: global___JointPositionUnit.ValueType = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["name", b"name", "unit", b"unit", "value", b"value"]) -> None: ...

global___JointPositionValue = JointPositionValue

@typing.final
class JointPositionsSchema(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    UNIT_FIELD_NUMBER: builtins.int
    JOINT_NAMES_FIELD_NUMBER: builtins.int
    unit: global___JointPositionUnit.ValueType
    @property
    def joint_names(self) -> google.protobuf.internal.containers.RepeatedScalarFieldContainer[builtins.str]: ...
    def __init__(
        self,
        *,
        unit: global___JointPositionUnit.ValueType = ...,
        joint_names: collections.abc.Iterable[builtins.str] | None = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["joint_names", b"joint_names", "unit", b"unit"]) -> None: ...

global___JointPositionsSchema = JointPositionsSchema

@typing.final
class JointPositionsValue(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    VALUES_FIELD_NUMBER: builtins.int
    @property
    def values(self) -> google.protobuf.internal.containers.RepeatedCompositeFieldContainer[global___JointPositionValue]: ...
    def __init__(
        self,
        *,
        values: collections.abc.Iterable[global___JointPositionValue] | None = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["values", b"values"]) -> None: ...

global___JointPositionsValue = JointPositionsValue

@typing.final
class JointVelocityValue(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    NAME_FIELD_NUMBER: builtins.int
    VALUE_FIELD_NUMBER: builtins.int
    UNIT_FIELD_NUMBER: builtins.int
    name: builtins.str
    value: builtins.float
    unit: global___JointVelocityUnit.ValueType
    def __init__(
        self,
        *,
        name: builtins.str = ...,
        value: builtins.float = ...,
        unit: global___JointVelocityUnit.ValueType = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["name", b"name", "unit", b"unit", "value", b"value"]) -> None: ...

global___JointVelocityValue = JointVelocityValue

@typing.final
class JointVelocitiesSchema(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    UNIT_FIELD_NUMBER: builtins.int
    JOINT_NAMES_FIELD_NUMBER: builtins.int
    unit: global___JointVelocityUnit.ValueType
    @property
    def joint_names(self) -> google.protobuf.internal.containers.RepeatedScalarFieldContainer[builtins.str]: ...
    def __init__(
        self,
        *,
        unit: global___JointVelocityUnit.ValueType = ...,
        joint_names: collections.abc.Iterable[builtins.str] | None = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["joint_names", b"joint_names", "unit", b"unit"]) -> None: ...

global___JointVelocitiesSchema = JointVelocitiesSchema

@typing.final
class JointVelocitiesValue(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    VALUES_FIELD_NUMBER: builtins.int
    @property
    def values(self) -> google.protobuf.internal.containers.RepeatedCompositeFieldContainer[global___JointVelocityValue]: ...
    def __init__(
        self,
        *,
        values: collections.abc.Iterable[global___JointVelocityValue] | None = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["values", b"values"]) -> None: ...

global___JointVelocitiesValue = JointVelocitiesValue

@typing.final
class JointTorqueValue(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    NAME_FIELD_NUMBER: builtins.int
    VALUE_FIELD_NUMBER: builtins.int
    UNIT_FIELD_NUMBER: builtins.int
    name: builtins.str
    value: builtins.float
    unit: global___JointTorqueUnit.ValueType
    def __init__(
        self,
        *,
        name: builtins.str = ...,
        value: builtins.float = ...,
        unit: global___JointTorqueUnit.ValueType = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["name", b"name", "unit", b"unit", "value", b"value"]) -> None: ...

global___JointTorqueValue = JointTorqueValue

@typing.final
class JointTorquesSchema(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    UNIT_FIELD_NUMBER: builtins.int
    JOINT_NAMES_FIELD_NUMBER: builtins.int
    unit: global___JointTorqueUnit.ValueType
    @property
    def joint_names(self) -> google.protobuf.internal.containers.RepeatedScalarFieldContainer[builtins.str]: ...
    def __init__(
        self,
        *,
        unit: global___JointTorqueUnit.ValueType = ...,
        joint_names: collections.abc.Iterable[builtins.str] | None = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["joint_names", b"joint_names", "unit", b"unit"]) -> None: ...

global___JointTorquesSchema = JointTorquesSchema

@typing.final
class JointTorquesValue(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    VALUES_FIELD_NUMBER: builtins.int
    @property
    def values(self) -> google.protobuf.internal.containers.RepeatedCompositeFieldContainer[global___JointTorqueValue]: ...
    def __init__(
        self,
        *,
        values: collections.abc.Iterable[global___JointTorqueValue] | None = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["values", b"values"]) -> None: ...

global___JointTorquesValue = JointTorquesValue

@typing.final
class CameraFrameSchema(google.protobuf.message.Message):
    """------------ *
    Camera Frame *
    ------------
    """

    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    WIDTH_FIELD_NUMBER: builtins.int
    HEIGHT_FIELD_NUMBER: builtins.int
    CHANNELS_FIELD_NUMBER: builtins.int
    width: builtins.int
    height: builtins.int
    channels: builtins.int
    def __init__(
        self,
        *,
        width: builtins.int = ...,
        height: builtins.int = ...,
        channels: builtins.int = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["channels", b"channels", "height", b"height", "width", b"width"]) -> None: ...

global___CameraFrameSchema = CameraFrameSchema

@typing.final
class CameraFrameValue(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    DATA_FIELD_NUMBER: builtins.int
    data: builtins.bytes
    def __init__(
        self,
        *,
        data: builtins.bytes = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["data", b"data"]) -> None: ...

global___CameraFrameValue = CameraFrameValue

@typing.final
class AudioFrameSchema(google.protobuf.message.Message):
    """----------- *
    Audio Frame *
    -----------
    """

    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    CHANNELS_FIELD_NUMBER: builtins.int
    SAMPLE_RATE_FIELD_NUMBER: builtins.int
    BYTES_PER_SAMPLE_FIELD_NUMBER: builtins.int
    channels: builtins.int
    sample_rate: builtins.int
    bytes_per_sample: builtins.int
    def __init__(
        self,
        *,
        channels: builtins.int = ...,
        sample_rate: builtins.int = ...,
        bytes_per_sample: builtins.int = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["bytes_per_sample", b"bytes_per_sample", "channels", b"channels", "sample_rate", b"sample_rate"]) -> None: ...

global___AudioFrameSchema = AudioFrameSchema

@typing.final
class AudioFrameValue(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    DATA_FIELD_NUMBER: builtins.int
    data: builtins.bytes
    def __init__(
        self,
        *,
        data: builtins.bytes = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["data", b"data"]) -> None: ...

global___AudioFrameValue = AudioFrameValue

@typing.final
class IMUSchema(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    VALUE_TYPE_FIELD_NUMBER: builtins.int
    value_type: global___IMUValueType.ValueType
    def __init__(
        self,
        *,
        value_type: global___IMUValueType.ValueType = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["value_type", b"value_type"]) -> None: ...

global___IMUSchema = IMUSchema

@typing.final
class IMUValue(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    X_FIELD_NUMBER: builtins.int
    Y_FIELD_NUMBER: builtins.int
    Z_FIELD_NUMBER: builtins.int
    W_FIELD_NUMBER: builtins.int
    x: builtins.float
    y: builtins.float
    z: builtins.float
    w: builtins.float
    def __init__(
        self,
        *,
        x: builtins.float = ...,
        y: builtins.float = ...,
        z: builtins.float = ...,
        w: builtins.float = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["w", b"w", "x", b"x", "y", b"y", "z", b"z"]) -> None: ...

global___IMUValue = IMUValue

@typing.final
class TimestampSchema(google.protobuf.message.Message):
    """--------- *
    Timestamp *
    ---------
    """

    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    START_SECONDS_FIELD_NUMBER: builtins.int
    START_NANOS_FIELD_NUMBER: builtins.int
    start_seconds: builtins.int
    start_nanos: builtins.int
    def __init__(
        self,
        *,
        start_seconds: builtins.int = ...,
        start_nanos: builtins.int = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["start_nanos", b"start_nanos", "start_seconds", b"start_seconds"]) -> None: ...

global___TimestampSchema = TimestampSchema

@typing.final
class TimestampValue(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    SECONDS_FIELD_NUMBER: builtins.int
    NANOS_FIELD_NUMBER: builtins.int
    seconds: builtins.int
    nanos: builtins.int
    def __init__(
        self,
        *,
        seconds: builtins.int = ...,
        nanos: builtins.int = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["nanos", b"nanos", "seconds", b"seconds"]) -> None: ...

global___TimestampValue = TimestampValue

@typing.final
class Value(google.protobuf.message.Message):
    """----- *
    Value *
    -----
    """

    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    NAME_FIELD_NUMBER: builtins.int
    TENSOR_FIELD_NUMBER: builtins.int
    JOINT_POSITIONS_FIELD_NUMBER: builtins.int
    JOINT_VELOCITIES_FIELD_NUMBER: builtins.int
    JOINT_TORQUES_FIELD_NUMBER: builtins.int
    CAMERA_FRAME_FIELD_NUMBER: builtins.int
    AUDIO_FRAME_FIELD_NUMBER: builtins.int
    IMU_FIELD_NUMBER: builtins.int
    TIMESTAMP_FIELD_NUMBER: builtins.int
    name: builtins.str
    @property
    def tensor(self) -> global___TensorValue: ...
    @property
    def joint_positions(self) -> global___JointPositionsValue: ...
    @property
    def joint_velocities(self) -> global___JointVelocitiesValue: ...
    @property
    def joint_torques(self) -> global___JointTorquesValue: ...
    @property
    def camera_frame(self) -> global___CameraFrameValue: ...
    @property
    def audio_frame(self) -> global___AudioFrameValue: ...
    @property
    def imu(self) -> global___IMUValue: ...
    @property
    def timestamp(self) -> global___TimestampValue: ...
    def __init__(
        self,
        *,
        name: builtins.str = ...,
        tensor: global___TensorValue | None = ...,
        joint_positions: global___JointPositionsValue | None = ...,
        joint_velocities: global___JointVelocitiesValue | None = ...,
        joint_torques: global___JointTorquesValue | None = ...,
        camera_frame: global___CameraFrameValue | None = ...,
        audio_frame: global___AudioFrameValue | None = ...,
        imu: global___IMUValue | None = ...,
        timestamp: global___TimestampValue | None = ...,
    ) -> None: ...
    def HasField(self, field_name: typing.Literal["audio_frame", b"audio_frame", "camera_frame", b"camera_frame", "imu", b"imu", "joint_positions", b"joint_positions", "joint_torques", b"joint_torques", "joint_velocities", b"joint_velocities", "tensor", b"tensor", "timestamp", b"timestamp", "value", b"value"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing.Literal["audio_frame", b"audio_frame", "camera_frame", b"camera_frame", "imu", b"imu", "joint_positions", b"joint_positions", "joint_torques", b"joint_torques", "joint_velocities", b"joint_velocities", "name", b"name", "tensor", b"tensor", "timestamp", b"timestamp", "value", b"value"]) -> None: ...
    def WhichOneof(self, oneof_group: typing.Literal["value", b"value"]) -> typing.Literal["tensor", "joint_positions", "joint_velocities", "joint_torques", "camera_frame", "audio_frame", "imu", "timestamp"] | None: ...

global___Value = Value

@typing.final
class ValueSchema(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    NAME_FIELD_NUMBER: builtins.int
    TENSOR_FIELD_NUMBER: builtins.int
    JOINT_POSITIONS_FIELD_NUMBER: builtins.int
    JOINT_VELOCITIES_FIELD_NUMBER: builtins.int
    JOINT_TORQUES_FIELD_NUMBER: builtins.int
    CAMERA_FRAME_FIELD_NUMBER: builtins.int
    AUDIO_FRAME_FIELD_NUMBER: builtins.int
    IMU_FIELD_NUMBER: builtins.int
    TIMESTAMP_FIELD_NUMBER: builtins.int
    name: builtins.str
    @property
    def tensor(self) -> global___TensorSchema: ...
    @property
    def joint_positions(self) -> global___JointPositionsSchema: ...
    @property
    def joint_velocities(self) -> global___JointVelocitiesSchema: ...
    @property
    def joint_torques(self) -> global___JointTorquesSchema: ...
    @property
    def camera_frame(self) -> global___CameraFrameSchema: ...
    @property
    def audio_frame(self) -> global___AudioFrameSchema: ...
    @property
    def imu(self) -> global___IMUSchema: ...
    @property
    def timestamp(self) -> global___TimestampSchema: ...
    def __init__(
        self,
        *,
        name: builtins.str = ...,
        tensor: global___TensorSchema | None = ...,
        joint_positions: global___JointPositionsSchema | None = ...,
        joint_velocities: global___JointVelocitiesSchema | None = ...,
        joint_torques: global___JointTorquesSchema | None = ...,
        camera_frame: global___CameraFrameSchema | None = ...,
        audio_frame: global___AudioFrameSchema | None = ...,
        imu: global___IMUSchema | None = ...,
        timestamp: global___TimestampSchema | None = ...,
    ) -> None: ...
    def HasField(self, field_name: typing.Literal["audio_frame", b"audio_frame", "camera_frame", b"camera_frame", "imu", b"imu", "joint_positions", b"joint_positions", "joint_torques", b"joint_torques", "joint_velocities", b"joint_velocities", "tensor", b"tensor", "timestamp", b"timestamp", "value_type", b"value_type"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing.Literal["audio_frame", b"audio_frame", "camera_frame", b"camera_frame", "imu", b"imu", "joint_positions", b"joint_positions", "joint_torques", b"joint_torques", "joint_velocities", b"joint_velocities", "name", b"name", "tensor", b"tensor", "timestamp", b"timestamp", "value_type", b"value_type"]) -> None: ...
    def WhichOneof(self, oneof_group: typing.Literal["value_type", b"value_type"]) -> typing.Literal["tensor", "joint_positions", "joint_velocities", "joint_torques", "camera_frame", "audio_frame", "imu", "timestamp"] | None: ...

global___ValueSchema = ValueSchema

@typing.final
class InputSchema(google.protobuf.message.Message):
    """------ *
    Inputs *
    ------
    """

    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    INPUTS_FIELD_NUMBER: builtins.int
    @property
    def inputs(self) -> google.protobuf.internal.containers.RepeatedCompositeFieldContainer[global___ValueSchema]: ...
    def __init__(
        self,
        *,
        inputs: collections.abc.Iterable[global___ValueSchema] | None = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["inputs", b"inputs"]) -> None: ...

global___InputSchema = InputSchema

@typing.final
class Input(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    INPUTS_FIELD_NUMBER: builtins.int
    @property
    def inputs(self) -> google.protobuf.internal.containers.RepeatedCompositeFieldContainer[global___Value]: ...
    def __init__(
        self,
        *,
        inputs: collections.abc.Iterable[global___Value] | None = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["inputs", b"inputs"]) -> None: ...

global___Input = Input

@typing.final
class OutputSchema(google.protobuf.message.Message):
    """------- *
    Outputs *
    -------
    """

    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    OUTPUTS_FIELD_NUMBER: builtins.int
    @property
    def outputs(self) -> google.protobuf.internal.containers.RepeatedCompositeFieldContainer[global___ValueSchema]: ...
    def __init__(
        self,
        *,
        outputs: collections.abc.Iterable[global___ValueSchema] | None = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["outputs", b"outputs"]) -> None: ...

global___OutputSchema = OutputSchema

@typing.final
class Output(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    OUTPUTS_FIELD_NUMBER: builtins.int
    @property
    def outputs(self) -> google.protobuf.internal.containers.RepeatedCompositeFieldContainer[global___Value]: ...
    def __init__(
        self,
        *,
        outputs: collections.abc.Iterable[global___Value] | None = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["outputs", b"outputs"]) -> None: ...

global___Output = Output
