"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
"""

import builtins
import collections.abc
import google.protobuf.descriptor
import google.protobuf.internal.containers
import google.protobuf.internal.enum_type_wrapper
import google.protobuf.message
import sys
import typing

if sys.version_info >= (3, 10):
    import typing as typing_extensions
else:
    import typing_extensions

DESCRIPTOR: google.protobuf.descriptor.FileDescriptor

class _ValueType:
    ValueType = typing.NewType("ValueType", builtins.int)
    V: typing_extensions.TypeAlias = ValueType

class _ValueTypeEnumTypeWrapper(google.protobuf.internal.enum_type_wrapper._EnumTypeWrapper[_ValueType.ValueType], builtins.type):
    DESCRIPTOR: google.protobuf.descriptor.EnumDescriptor
    TENSOR: _ValueType.ValueType  # 0
    JOINT_POSITIONS: _ValueType.ValueType  # 1
    JOINT_VELOCITIES: _ValueType.ValueType  # 2
    JOINT_TORQUES: _ValueType.ValueType  # 3
    CAMERA_FRAME: _ValueType.ValueType  # 4
    AUDIO_FRAME: _ValueType.ValueType  # 5
    IMU: _ValueType.ValueType  # 6
    TIMESTAMP: _ValueType.ValueType  # 7

class ValueType(_ValueType, metaclass=_ValueTypeEnumTypeWrapper): ...

TENSOR: ValueType.ValueType  # 0
JOINT_POSITIONS: ValueType.ValueType  # 1
JOINT_VELOCITIES: ValueType.ValueType  # 2
JOINT_TORQUES: ValueType.ValueType  # 3
CAMERA_FRAME: ValueType.ValueType  # 4
AUDIO_FRAME: ValueType.ValueType  # 5
IMU: ValueType.ValueType  # 6
TIMESTAMP: ValueType.ValueType  # 7
global___ValueType = ValueType

@typing.final
class TensorValue(google.protobuf.message.Message):
    """------ *
    Tensor *
    ------
    """

    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    SHAPE_FIELD_NUMBER: builtins.int
    DATA_FIELD_NUMBER: builtins.int
    @property
    def shape(self) -> google.protobuf.internal.containers.RepeatedScalarFieldContainer[builtins.int]: ...
    @property
    def data(self) -> google.protobuf.internal.containers.RepeatedScalarFieldContainer[builtins.float]: ...
    def __init__(
        self,
        *,
        shape: collections.abc.Iterable[builtins.int] | None = ...,
        data: collections.abc.Iterable[builtins.float] | None = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["data", b"data", "shape", b"shape"]) -> None: ...

global___TensorValue = TensorValue

@typing.final
class JointPosition(google.protobuf.message.Message):
    """---------------- *
    Joint Positions *
    ----------------
    """

    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    JOINT_NAME_FIELD_NUMBER: builtins.int
    DEGREES_FIELD_NUMBER: builtins.int
    joint_name: builtins.str
    degrees: builtins.float
    def __init__(
        self,
        *,
        joint_name: builtins.str = ...,
        degrees: builtins.float = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["degrees", b"degrees", "joint_name", b"joint_name"]) -> None: ...

global___JointPosition = JointPosition

@typing.final
class JointPositionsValue(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    POSITIONS_FIELD_NUMBER: builtins.int
    @property
    def positions(self) -> google.protobuf.internal.containers.RepeatedCompositeFieldContainer[global___JointPosition]: ...
    def __init__(
        self,
        *,
        positions: collections.abc.Iterable[global___JointPosition] | None = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["positions", b"positions"]) -> None: ...

global___JointPositionsValue = JointPositionsValue

@typing.final
class JointVelocity(google.protobuf.message.Message):
    """---------------- *
    Joint Velocities *
    ----------------
    """

    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    JOINT_NAME_FIELD_NUMBER: builtins.int
    DEGREES_PER_SECOND_FIELD_NUMBER: builtins.int
    joint_name: builtins.str
    degrees_per_second: builtins.float
    def __init__(
        self,
        *,
        joint_name: builtins.str = ...,
        degrees_per_second: builtins.float = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["degrees_per_second", b"degrees_per_second", "joint_name", b"joint_name"]) -> None: ...

global___JointVelocity = JointVelocity

@typing.final
class JointVelocitiesValue(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    VELOCITIES_FIELD_NUMBER: builtins.int
    @property
    def velocities(self) -> google.protobuf.internal.containers.RepeatedCompositeFieldContainer[global___JointVelocity]: ...
    def __init__(
        self,
        *,
        velocities: collections.abc.Iterable[global___JointVelocity] | None = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["velocities", b"velocities"]) -> None: ...

global___JointVelocitiesValue = JointVelocitiesValue

@typing.final
class JointTorque(google.protobuf.message.Message):
    """-------------- *
    Joint Torques *
    --------------
    """

    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    JOINT_NAME_FIELD_NUMBER: builtins.int
    NEWTON_METERS_FIELD_NUMBER: builtins.int
    joint_name: builtins.str
    newton_meters: builtins.float
    def __init__(
        self,
        *,
        joint_name: builtins.str = ...,
        newton_meters: builtins.float = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["joint_name", b"joint_name", "newton_meters", b"newton_meters"]) -> None: ...

global___JointTorque = JointTorque

@typing.final
class JointTorquesValue(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    TORQUES_FIELD_NUMBER: builtins.int
    @property
    def torques(self) -> google.protobuf.internal.containers.RepeatedCompositeFieldContainer[global___JointTorque]: ...
    def __init__(
        self,
        *,
        torques: collections.abc.Iterable[global___JointTorque] | None = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["torques", b"torques"]) -> None: ...

global___JointTorquesValue = JointTorquesValue

@typing.final
class CameraFrameValue(google.protobuf.message.Message):
    """------------ *
    Camera Frame *
    ------------
    """

    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    WIDTH_FIELD_NUMBER: builtins.int
    HEIGHT_FIELD_NUMBER: builtins.int
    CHANNELS_FIELD_NUMBER: builtins.int
    DATA_FIELD_NUMBER: builtins.int
    width: builtins.int
    height: builtins.int
    channels: builtins.int
    @property
    def data(self) -> google.protobuf.internal.containers.RepeatedScalarFieldContainer[builtins.float]: ...
    def __init__(
        self,
        *,
        width: builtins.int = ...,
        height: builtins.int = ...,
        channels: builtins.int = ...,
        data: collections.abc.Iterable[builtins.float] | None = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["channels", b"channels", "data", b"data", "height", b"height", "width", b"width"]) -> None: ...

global___CameraFrameValue = CameraFrameValue

@typing.final
class AudioFrameValue(google.protobuf.message.Message):
    """----------- *
    Audio Frame *
    -----------
    """

    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    CHANNELS_FIELD_NUMBER: builtins.int
    SAMPLE_RATE_FIELD_NUMBER: builtins.int
    DATA_FIELD_NUMBER: builtins.int
    channels: builtins.int
    sample_rate: builtins.int
    @property
    def data(self) -> google.protobuf.internal.containers.RepeatedScalarFieldContainer[builtins.float]: ...
    def __init__(
        self,
        *,
        channels: builtins.int = ...,
        sample_rate: builtins.int = ...,
        data: collections.abc.Iterable[builtins.float] | None = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["channels", b"channels", "data", b"data", "sample_rate", b"sample_rate"]) -> None: ...

global___AudioFrameValue = AudioFrameValue

@typing.final
class IMUValue(google.protobuf.message.Message):
    """--- *
    IMU *
    ---
    """

    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    X_FIELD_NUMBER: builtins.int
    Y_FIELD_NUMBER: builtins.int
    Z_FIELD_NUMBER: builtins.int
    W_FIELD_NUMBER: builtins.int
    x: builtins.float
    y: builtins.float
    z: builtins.float
    w: builtins.float
    def __init__(
        self,
        *,
        x: builtins.float = ...,
        y: builtins.float = ...,
        z: builtins.float = ...,
        w: builtins.float = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["w", b"w", "x", b"x", "y", b"y", "z", b"z"]) -> None: ...

global___IMUValue = IMUValue

@typing.final
class TimestampValue(google.protobuf.message.Message):
    """--------- *
    Timestamp *
    ---------
    """

    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    SECONDS_FIELD_NUMBER: builtins.int
    NANOS_FIELD_NUMBER: builtins.int
    START_SECONDS_FIELD_NUMBER: builtins.int
    START_NANOS_FIELD_NUMBER: builtins.int
    seconds: builtins.int
    nanos: builtins.int
    start_seconds: builtins.int
    start_nanos: builtins.int
    def __init__(
        self,
        *,
        seconds: builtins.int = ...,
        nanos: builtins.int = ...,
        start_seconds: builtins.int = ...,
        start_nanos: builtins.int = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["nanos", b"nanos", "seconds", b"seconds", "start_nanos", b"start_nanos", "start_seconds", b"start_seconds"]) -> None: ...

global___TimestampValue = TimestampValue

@typing.final
class Value(google.protobuf.message.Message):
    """----- *
    Value *
    -----
    """

    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    VALUE_NAME_FIELD_NUMBER: builtins.int
    TENSOR_FIELD_NUMBER: builtins.int
    JOINT_POSITIONS_FIELD_NUMBER: builtins.int
    JOINT_VELOCITIES_FIELD_NUMBER: builtins.int
    JOINT_TORQUES_FIELD_NUMBER: builtins.int
    CAMERA_FRAME_FIELD_NUMBER: builtins.int
    AUDIO_FRAME_FIELD_NUMBER: builtins.int
    IMU_FIELD_NUMBER: builtins.int
    TIMESTAMP_FIELD_NUMBER: builtins.int
    value_name: builtins.str
    @property
    def tensor(self) -> global___TensorValue: ...
    @property
    def joint_positions(self) -> global___JointPositionsValue: ...
    @property
    def joint_velocities(self) -> global___JointVelocitiesValue: ...
    @property
    def joint_torques(self) -> global___JointTorquesValue: ...
    @property
    def camera_frame(self) -> global___CameraFrameValue: ...
    @property
    def audio_frame(self) -> global___AudioFrameValue: ...
    @property
    def imu(self) -> global___IMUValue: ...
    @property
    def timestamp(self) -> global___TimestampValue: ...
    def __init__(
        self,
        *,
        value_name: builtins.str = ...,
        tensor: global___TensorValue | None = ...,
        joint_positions: global___JointPositionsValue | None = ...,
        joint_velocities: global___JointVelocitiesValue | None = ...,
        joint_torques: global___JointTorquesValue | None = ...,
        camera_frame: global___CameraFrameValue | None = ...,
        audio_frame: global___AudioFrameValue | None = ...,
        imu: global___IMUValue | None = ...,
        timestamp: global___TimestampValue | None = ...,
    ) -> None: ...
    def HasField(self, field_name: typing.Literal["audio_frame", b"audio_frame", "camera_frame", b"camera_frame", "imu", b"imu", "joint_positions", b"joint_positions", "joint_torques", b"joint_torques", "joint_velocities", b"joint_velocities", "tensor", b"tensor", "timestamp", b"timestamp", "value", b"value"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing.Literal["audio_frame", b"audio_frame", "camera_frame", b"camera_frame", "imu", b"imu", "joint_positions", b"joint_positions", "joint_torques", b"joint_torques", "joint_velocities", b"joint_velocities", "tensor", b"tensor", "timestamp", b"timestamp", "value", b"value", "value_name", b"value_name"]) -> None: ...
    def WhichOneof(self, oneof_group: typing.Literal["value", b"value"]) -> typing.Literal["tensor", "joint_positions", "joint_velocities", "joint_torques", "camera_frame", "audio_frame", "imu", "timestamp"] | None: ...

global___Value = Value

@typing.final
class ValueSchema(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    NAME_FIELD_NUMBER: builtins.int
    VALUE_TYPE_FIELD_NUMBER: builtins.int
    name: builtins.str
    value_type: global___ValueType.ValueType
    def __init__(
        self,
        *,
        name: builtins.str = ...,
        value_type: global___ValueType.ValueType = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["name", b"name", "value_type", b"value_type"]) -> None: ...

global___ValueSchema = ValueSchema

@typing.final
class Input(google.protobuf.message.Message):
    """------ *
    Inputs *
    ------
    """

    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    INPUTS_FIELD_NUMBER: builtins.int
    @property
    def inputs(self) -> google.protobuf.internal.containers.RepeatedCompositeFieldContainer[global___Value]: ...
    def __init__(
        self,
        *,
        inputs: collections.abc.Iterable[global___Value] | None = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["inputs", b"inputs"]) -> None: ...

global___Input = Input

@typing.final
class InputSchema(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    INPUTS_FIELD_NUMBER: builtins.int
    @property
    def inputs(self) -> google.protobuf.internal.containers.RepeatedCompositeFieldContainer[global___ValueSchema]: ...
    def __init__(
        self,
        *,
        inputs: collections.abc.Iterable[global___ValueSchema] | None = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["inputs", b"inputs"]) -> None: ...

global___InputSchema = InputSchema

@typing.final
class Output(google.protobuf.message.Message):
    """------- *
    Outputs *
    -------
    """

    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    OUTPUTS_FIELD_NUMBER: builtins.int
    @property
    def outputs(self) -> google.protobuf.internal.containers.RepeatedCompositeFieldContainer[global___Value]: ...
    def __init__(
        self,
        *,
        outputs: collections.abc.Iterable[global___Value] | None = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["outputs", b"outputs"]) -> None: ...

global___Output = Output

@typing.final
class OutputSchema(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    OUTPUTS_FIELD_NUMBER: builtins.int
    @property
    def outputs(self) -> google.protobuf.internal.containers.RepeatedCompositeFieldContainer[global___ValueSchema]: ...
    def __init__(
        self,
        *,
        outputs: collections.abc.Iterable[global___ValueSchema] | None = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["outputs", b"outputs"]) -> None: ...

global___OutputSchema = OutputSchema
